### ISSUE TITLE
Why migrate from Gradle to Maven?

### ISSUE THREAD

**Issue by Xerus2000** [dlemmermann/PreferencesFX#18]
Gradle is much less verbose and much more versatile than maven. Why would you go that step back?

**Comment by dlemmermann** [comment]
Because I hate Gradle. As simple as that. I have been using Maven for years and found nothing seriously wrong with it. I do like verbosity. I do like the declarative approach. Also, all my projects use Maven and this way I do not have to switch back and forth. BTW, there are quite a few people who would disagree that using Maven is "a step back". The students who implemented this project initially used Gradle and struggled with it, too. When they switched to Maven they said that it made their life a whole lot easier.
