### ISSUE TITLE
Reduce coupling

### ISSUE THREAD

**Issue by Xerus2000** [dlemmermann/PreferencesFX#26]
Currently, most objects store references the each other:
PreferencesFX stores everything
The view keeps references to storage and other stuff
Etc.

This is not good design and makes it harder to customise and improve the individual components.

**Comment by martinfrancois** [comment]
Hi @Xerus2000,
We tried to have the least amount of coupling possible, while still preserving ease of use of the API. For example, we used dependency injection wherever we could.
Could you please elaborate on which parts of the code you find to have too much coupling and what parts you would like to customize and improve, and are unable to do so?
Thanks!

**Comment by Xerus2000** [comment]
Well, as I said, PreferencesFX stores a reference to the View and the Store, and the View then also stores a reference to the Store. I observed this pattern on multiple occasions and it makes everything intertwined.

**Comment by martinfrancois** [comment]
The only view that has a reference to the `StorageHandler` is `PreferencesFxDialog`, and it gets the `StorageHandler` by calling `model.getStorageHandler()`. This allows for dependency injection of the `StorageHandler`, especially since the `PreferencesFxDialog` gets the `PreferencesFxModel` passed in with the constructor parameters. To me, this is not bad design.
What would you propose here to reduce the coupling even further? I mean sure, we could delegate the calls to `StorageHandler` we currently do in `PreferencesFxDialog` to `PreferencesFxModel`, but I don't see how that would reduce coupling, since then it would just be `PreferencesFxModel` indirectly calling the `StorageHandler` methods, which wouldn't make any difference.
Thanks!

**Comment by martinfrancois** [comment]
Since there was no response, I will close this issue. Feel free to open it up again or create another issue should you still run into issues.
