### ISSUE TITLE
Is there a way to allow user to add new element to ListProperty?

### ISSUE THREAD

**Issue by sdaskaliesku** [dlemmermann/PreferencesFX#42]
Simplest example, ListProperty<String> names = ...; , on UI user may see a ListView with an TextField and Button.

If this functionality does not exists right now, could you please suggest me an entry point to start implementing this?

**Comment by martinfrancois** [comment]
Hi @sdaskaliesku,
Do you mean something like this?
https://docs.oracle.com/javafx/2/ui_controls/img/table-sample.png

**Comment by sdaskaliesku** [comment]
Hi, @martinfrancois!
Exactly!

**Comment by sdaskaliesku** [comment]
For now I see two possible solutions:
1. Iterate over all PreferencesFxView nodes, find appropriate one and add required nodes for specific group in runtime.
But this solution adds a lot of complexity, especially with alignment.
2. Again, iterate over all nodes add event listener for click on Category (in case there is a TreeView) and open additional Dialog which will render required Nodes. In this case additional Nodes can be declared in regular fxml file.
From UX perspective of view, it isn't the best solution.

**Comment by martinfrancois** [comment]
Hi @sdaskaliesku 

Do I understand that correctly? You just want to use this for a particular setting in the PreferencesFX window, right?
If so, your two proposed solutions are waaaay to complex. We designed PreferencesFX with the ability to use custom controls for settings in mind.
Have a look at the `README` and search for `// Custom Control`:
```java
IntegerProperty customControlProperty = new SimpleIntegerProperty(42);
IntegerField customControl = Field.ofIntegerType(customControlProperty).render(
  new IntegerSliderControl(0, 42));
Setting.of("Favorite Number", customControl, customControlProperty);
```
This shows you how to use a custom control in a setting.
But instead of using `Field.ofIntegerType(...)`, since you use a list, you would need to use something like this:
```java
Field.ofMultiSelectionType(items, selections)
            .label(description)
            .render(new AddElementListViewControl<>())
```
The class `AddElementListViewControl` would be your custom control, containing the list view with the add button and the text box below it, like in the screenshot. As a base for your implementation, you can reuse the code from the `SimpleListViewControl` class and add a textbox to the bottom with a button, and you should be done.

I hope it's clear enough, else don't hesitate to ask back!

**Comment by sdaskaliesku** [comment]
ooooooooooh, that's awesome! Somehow I've missed this example.
Thank you!

Just made a small sample and it worked exactly as I need.

However in case saving settings I faced a minor issue (looks like related to gson), while providing custom cell factory for list view, there is a class cast exception, but it's not a problem for me, since I'm using custom implementation of StorageHandler.
StorageHandlerImpl#loadObservableList deserializes objects into com.google.gson.internal.LinkedTreeMap.Node

**Comment by martinfrancois** [comment]
I'm glad this could be resolved for you! I'm closing this issue then, feel free to reopen it should there be anything left.
