### ISSUE TITLE
Invalid dependency into Maven Central

### ISSUE THREAD

**Issue by gallandarakhneorg** [dlemmermann/PreferencesFX#70]
The stable release 11.1.0 of PreferencesFX on Maven Central has a SNAPSHOT dependency.

It avoid to use a version greater than 2.1.0.

**Comment by martinfrancois** [comment]
Hi @gallandarakhneorg
I'm not sure, but do you mean the snapshot dependency to ControlsFX? This was necessary, since for a long time there was no ControlsFX release that supported Java 9 and up outside of this snapshot release.
However now that ControlsFX 11.0.0 is released, we should switch to this version instead.
Is that what you meant?

**Comment by martinfrancois** [comment]
Implemented in version `8.3.0` and `11.3.0`
